spring.application.name=server

# Database connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/ims
spring.datasource.username=imron
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=60000
spring.cache.type=redis

jwt.secret=2a5da85c4d67135be14296e9741200abfff4955cc3b4bcd6e748cb11ab3d81b1
jwt.expired=30 * 24 * 60 * 60 * 1000